#pragma once
#ifndef ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_LIFECYCLE_MSGS_H
#define ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_LIFECYCLE_MSGS_H

#ifdef ROS
#endif

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_BEGIN

namespace lifecycle_msgs {
namespace msg {}
namespace srv {}
}  // namespace lifecycle_msgs

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_END

#endif  // ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_LIFECYCLE_MSGS_H
