#pragma once
#ifndef ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_RCL_INTERFACES_H
#define ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_RCL_INTERFACES_H

#ifdef ROS
#endif

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_BEGIN

namespace rcl_interfaces {
namespace msg {}
namespace srv {}
}  // namespace rcl_interfaces

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_END

#endif  // ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_RCL_INTERFACES_H
