#pragma once
#ifndef ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_ACTION_MSGS_H
#define ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_ACTION_MSGS_H

#ifdef ROS
#endif

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_BEGIN

namespace action_msgs {
namespace msg {}
namespace srv {}
}  // namespace action_msgs

ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_NAMESPACE_END

#endif  // ARDUINO_MSGPACK_ROS_INTERFACES_RCL_INTERFACES_ACTION_MSGS_H
